### ISSUE TITLE
Example test

### ISSUE THREAD

**Issue by matq007** [keichi/mpEDM#85]
Hi @keichi, awesome implementation! Could you please provide some example on how to run the tool? For example a Jupyter notebook tutorial or something along that line? Thank you.

**Comment by keichi** [comment]
Thanks for reaching out to us @matq007! Unfortunately, we don't have a tutorial or example yet. If you need all-to-all CCM, you can use the `cross_mapping_bench` executable. Otherwise, let me know your use case so we can help you.
